### ISSUE TITLE
Add implementation of red-black tree

### ISSUE THREAD

**Issue by SiddharthaAnand** [SiddharthaAnand/datastructures#4]
Add the implementation of red-black tree. It can be in any programming language though preferred ones are Java, C, Cpp or python.

**Comment by egakupi** [comment]
Hello! I would like to try on this.

**Comment by tchainzzz** [comment]
I could take a crack at that? Will probably be in Java.

**Comment by SiddharthaAnand** [comment]
> I could take a crack at that? Will probably be in Java.

Sure you can start on this.

**Comment by aitorres** [comment]
Would you like having multiple implementations in several languages? I can develop one in Python. I'll start working on it and add a PR when it's done.

**Comment by tchainzzz** [comment]
@aitorres Want to coordinate so we can make sure our code is consistent (stylistically, methods, etc.)?

**Comment by dRadest** [comment]
Is anybody working on Java implementation? If not, I can give it a go.

**Comment by SiddharthaAnand** [comment]
Sure. You can start working on it.

**Comment by MaurizioKorri** [comment]
ill try to implement it in java

**Comment by bermylle** [comment]
Hello is this solved or claimed? Sorry first timer! Ill try with java if its ok

**Comment by SiddharthaAnand** [comment]
Hi @bermylle , Sure you can start on this.

**Comment by bermylle** [comment]
> Hi @bermylle , Sure you can start on this.

Ok thank you! Will work on it.

**Comment by boomwakalaka** [comment]
Hi, can I try to develop with Java, even i see others developers before me using the same language?
It will be my first contribution, i'm just a begginer

**Comment by igrvlhlb** [comment]
I can add it in C in a few days (I'm a bit busy right now)

**Comment by Shubhangi2901** [comment]
I can claim this if not resolved yet! @SiddharthaAnand

**Comment by encarcio** [comment]
If the issue is still open and not resolved then may I claim the issue @SiddharthaAnand ?

**Comment by PanchalShubham** [comment]
If the issue is still open I can work on in it any language C,C++,Java or Python

**Comment by PanchalShubham** [comment]
> Definitely. @PanchalShubham @Shubhangi2901 Please go ahead. @encarcio @boomwakalaka
> Will create seperate issues and integrate your PRs.

Let me the one you need C/C++/Java or Python

**Comment by PanchalShubham** [comment]
I have written the Java Implementation but I'm unable to push as I'm getting access denied. Let me know further steps.

**Comment by SiddharthaAnand** [comment]
@PanchalShubham 
Please follow the steps:
1. Fork this repository into your own.
2. Make the changes.
3. Push your changes in your repository.
4. Open a Pull Request with this repository.

**Comment by PanchalShubham** [comment]
I have created a PR please check it out

**Comment by sulemangit** [comment]
first time here, can I pick this up?

**Comment by SiddharthaAnand** [comment]
This issue is Closed. You can go over other issues and pick some from those.
