### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by SiddharthaAnand** [SiddharthaAnand/datastructures#5]
Add this file for making first-time users more welcoming and friendly while contributing to this repository. This file might include but not limited to steps to report bugs, add unit tests, improve code documentation etc.

**Comment by swaager** [comment]
Can i work in this issue?

**Comment by nivedithapatil** [comment]
i would love to work on this issue .

**Comment by SiddharthaAnand** [comment]
> Can i work in this issue?

Sure. You can work on this issue.

**Comment by SiddharthaAnand** [comment]
> i would love to work on this issue .

You too can start working on this issue too.

**Comment by RochelleWolfe** [comment]
I'll give it a go!
